### PR TITLE
Add experimental channel

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Needed for https://github.com/ros-visualization/rviz/pull/1715

/cc @wolfv

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
I have merged pyqt-builder yesterday on conda forge. Maybe we don't need it anymore?

**Comment by Tobias-Fischer** [comment]
See #19 instead

**Pull request closed without merging**
